# This file was generated by GoReleaser. DO NOT EDIT.
cask "envio" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1e0be7790aea00e6aa2e981899a2c081a0a4f4b6f264b9a9b2732a33a60acf4c"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "baaff1de12ac677df710d1ceec99a0408a8c65adfedc7d834aa40d5a1f6bb34c"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c20100d2b232fc77b91f8e4982f1457110f6b9354997b1fd7e1f646c85be1741"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd4bf30ead8bb7c93da2ed736c99ba5293cfc26ebaa25ab97706c55b0ac9ba22"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envio"
  desc "Zero-knowledge environment variable and secret management CLI"
  homepage "https://github.com/Team-NEEEE/envio-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envio"

  # No zap stanza required

end
