# This file was generated by GoReleaser. DO NOT EDIT.
cask "envio" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "7c2e304464462e7a61814401d5049173dc9db2af78eb6afcf7f2bb13b76509f1"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98020f3e7c010e9dc91169c4705f4dd473cf5e2ec3eb3301be19bdf51a1f544a"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f7bd5b27d99091f0206f699584e373ba96da6086b5218ec67107bdd8a4b49bc"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f29bc101385e5b60b54de437fe74845c572768c0352d3d3bcf854f26a535d333"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envio"
  desc "Zero-knowledge environment variable and secret management CLI"
  homepage "https://github.com/Team-NEEEE/envio-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envio"

  # No zap stanza required

end
