# This file was generated by GoReleaser. DO NOT EDIT.
cask "envio" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8a8d0e09bda03f1ff407243a2c5ed0980ea01fc2d6996d4e00fda7a07b3715ae"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "131499a0a4c9f9f853cf1bb6e16c207df63c1e778c51e5f82ada20225b5cfb7e"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba3aeefa74c92f27bec67a81571a92b4ff75297eb38e329a7e2175a04b2e222e"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebb99ae1af38e39b948a8625bff4e217fa1f6da7a010ae560df227455bb904dc"
      url "https://github.com/Team-NEEEE/envio-cli/releases/download/v#{version}/envio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envio"
  desc "Zero-knowledge environment variable and secret management CLI"
  homepage "https://github.com/Team-NEEEE/envio-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envio"

  # No zap stanza required

end
